### ISSUE TITLE
启用插件后未生效

### ISSUE THREAD

**Issue by fengyunljp** [halo-sigs/plugin-highlightjs#1]
使用的是默认的 earth 主题

启用插件后，看到js文件引用成功输出至HTML页面，但代码高亮未生效。

通过代码注入的方式添加 `<script>hljs.highlightAll();</script>` 后成功渲染。

不知道是不是因为 1.x 迁移的文章的缘故

文章内容代码部分如下：

```
<pre><code>some code...
        some code...
</code></pre>
```

**Comment by JohnNiang** [comment]
Hi @fengyunljp ，有尝试在 hilightjs 插件中设置高亮主题么，请参考下面的截图：

![image](https://user-images.githubusercontent.com/16865714/205692144-c50c6936-2b8f-4d81-9659-41f890c9d012.png)

**Comment by fengyunljp** [comment]
好像确实是这个原因，十分感谢！
