### ISSUE TITLE
复制按钮不显示

### ISSUE THREAD

**Issue by godcop** [halo-sigs/plugin-highlightjs#18]
<img width="193" alt="Snipaste_2024-06-18_21-36-25" src="https://github.com/halo-sigs/plugin-highlightjs/assets/18001513/99232c24-de30-404d-b473-469c2fd858d7">
所有主题都是这样

**Comment by verkyer** [comment]
同样问题浏览器是 百分浏览器（https://www.centbrowser.cn/）
版本 5.1.1130.129（正式版本） （64 位） (Chromium 118.0.5993.159)
![44857f98394acd1adb2dfa18cc5a171](https://github.com/user-attachments/assets/71bc0507-95de-42fa-864e-91f888fcaed7)

**Comment by ruibaby** [comment]
hi @verkyer @godcop,

我这里提交了一个兼容方案，请帮忙测试一下：https://github.com/halo-sigs/plugin-highlightjs/pull/31
