### ISSUE TITLE
反引号包裹的代码未渲染

### ISSUE THREAD

**Issue by BennettChina** [halo-sigs/plugin-highlightjs#30]
我在默认的 `Earth` 主题尝试发现未渲染  \`code\` 的代码块。

<img width="942" alt="image" src="https://github.com/user-attachments/assets/35cca8ac-4225-435f-9da1-4c3f6f557661">

halo@2.19.3
plugin-highlightjs@1.3.1

**Comment by ruibaby** [comment]
这个问题与这个插件无关，详情见：

- https://github.com/halo-dev/theme-earth/issues/42
- https://github.com/halo-dev/theme-earth/pull/132

**Comment by BennettChina** [comment]
OK，了解了，那我去插件那边提 issue（本来用的 Next ， 用 Earth 对比测试的）。

**Comment by ruibaby** [comment]
> OK，了解了，那我去插件那边提 issue（本来用的 Next ， 用 Earth 对比测试的）。

这是主题的问题，你去主题设置选择内容样式就行了。

<img width="600" alt="image" src="https://github.com/user-attachments/assets/0203ee31-d4cf-4f5f-a897-3c4cb37e4fa9">
