### ISSUE TITLE
个别语言无法支持 ，如 TCL

### ISSUE THREAD

**Issue by zeng-yq** [halo-sigs/plugin-highlightjs#32]
个别语言无法支持 ，如 TCL，在 markdown 编辑时能高亮：
![image](https://github.com/user-attachments/assets/e54b8d0e-0b32-4b3f-91e5-30629a05a86c)
前端页面不能高亮：
![image](https://github.com/user-attachments/assets/b0c72dfd-8e26-42b2-85e2-7ea64083099e)

**Comment by ruibaby** [comment]
这看起来是主题自己实现的代码高亮，建议向主题反馈。
